package com.nathanosman.heidelbergreader;

import android.content.Context;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

/**
 * RecyclerView adapter that displays a list of questions
 */
public class QuestionAdapter extends RecyclerView.Adapter<QuestionAdapter.ViewHolder> {

    /**
     * Interface for navigation events generated by the adapter
     */
    interface Listener {
        void onNavigate(int index);
    }

    private Context mContext;
    private Listener mListener;

    private View.OnClickListener mOnClickListener = new View.OnClickListener() {

        @Override
        public void onClick(View view) {
            mListener.onNavigate((int) view.getTag());
        }
    };

    private QuestionService.LocalBinder mBinder;

    /**
     * Create a new question adapter
     * @param context use this context for string resources
     * @param listener notification for navigation events
     */
    QuestionAdapter(Context context, Listener listener) {
        mContext = context;
        mListener = listener;
    }

    /**
     * Set the binder for retrieving question data
     */
    void setBinder(QuestionService.LocalBinder binder) {
        mBinder = binder;
        notifyDataSetChanged();
    }

    /**
     * View holder for an individual question
     */
    static class ViewHolder extends RecyclerView.ViewHolder {

        private TextView mNumber;
        private TextView mTitle;
        private TextView mSummary;

        ViewHolder(View itemView) {
            super(itemView);

            mNumber = itemView.findViewById(R.id.question_list_number);
            mTitle = itemView.findViewById(R.id.question_list_title);
            mSummary = itemView.findViewById(R.id.question_list_summary);
        }
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new ViewHolder(
                LayoutInflater.from(parent.getContext()).inflate(
                        R.layout.question_list_content,
                        parent,
                        false
                )
        );
    }

    @Override
    public void onBindViewHolder(ViewHolder holder, int position) {

        // Retrieve the question for the specified index
        Question question = mBinder.getQuestion(position);

        // Populate the view holder with the question data
        holder.mNumber.setText(mContext.getString(R.string.adapter_question_number, question.getNumber()));
        holder.mTitle.setText(question.getQuestion());
        holder.mSummary.setText(question.getAnswer());

        holder.itemView.setTag(position);
        holder.itemView.setOnClickListener(mOnClickListener);
    }

    @Override
    public int getItemCount() {
        return mBinder != null ? mBinder.getQuestionCount() : 0;
    }
}
